
class Stages_names:
    START = 'start'
    HOME = 'home'
    OTHER = 'other'
    PASSWORDS = 'passwords'
    SETTING_PASSWORDS = 'setting_passwords'
    MAIL = 'mail'
    PRESETS = 'presets'
    FORM = 'form'
    FAC = 'fac'
    GROUP_SELECT = 'group_select'
    SESSION_GROUP_SELECT = 'session_group_select'
    SUBGROUP = 'subgroup'
    SCHEDULE_TYPE = 'schedule_type'
    DATE_SELECT = 'date_select'
    WEEK_SELECT = 'week_select'
    SETTINGS_WEEK = 'settings_week'
